### ISSUE TITLE
Make fails with nginx v1.11.3 / v1.10.1

### ISSUE THREAD

**Issue by DamnFinn** [grahamedgecombe/nginx-ct#12]
- using nginx-ct release version 1.3.0
- using OpenSSL version 1.0.2h (on Debian jessie 8.5)
- using nginx mainline version 1.11.3 and stable version 1.10.1 - but works with previous stable version 1.10.0
- nginx configured with add-module for nginx-ct:

`./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-file-aio --with-http_v2_module --with-ipv6 --add-module=../nginx-ct-1.3.0`

Occurred error on _make_:

```
objs/ngx_modules.o \
-ldl -lpthread -lpthread -lcrypt -lpcre -lssl -lcrypto -ldl -lz \
-Wl,-E
objs/addon/nginx-ct-1.3.0/ngx_ssl_ct_module.o: In function `ngx_ssl_ct_ext_cb':
~/nginx-current/nginx-1.11.3/../nginx-ct-1.3.0/ngx_ssl_ct_module.c:197: undefined reference to `ssl_get_server_send_pkey'
collect2: error: ld returned 1 exit status
objs/Makefile:354: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '~/nginx-current/nginx-1.11.3'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by grahamedgecombe** [comment]
Does d9ef01ecc5d99df2c6acd680ad174d1e5571684e fix this?

**Comment by DamnFinn** [comment]
Yes, it works. Thank you.
